//
//  CommentModel.swift
//  projectX
//
//  Created by Radomyr Bezghin on 9/10/20.
//  Copyright © 2020 Radomyr Bezghin. All rights reserved.
//

//comments
//* date
//* postID
//* userInfo{  name userID imageURL }
//* text
//* likes count
import FirebaseFirestore
struct Comment{
    /// A unique ID identifying the post, generated by Firestore.
    var documentID: String

    /// post where comment is posted.
    var postID: String

    /// The number of likes of the post.
    var likes: Int

    /// User information duplicated in the comment object.
    var userInfo: User
    
    /// The body text of the comment.
    var text: String

    /// The date the comment was posted.
    var date: Date

}
extension Comment{
    public init(postID: String,
                userInfo: User,
                text: String,
                likes: Int,
                date: Date) {
        let document = Firestore.firestore().comments.document() // returns a brand new document
        documentID = document.documentID
        self.postID = postID
        self.userInfo = userInfo
        self.text = text
        self.likes = likes
        self.date = date
    }
    /// used to generate json like format for db
    var documentData: [String: Any] {
      return [
        "postID": postID,
        "userInfo": userInfo.documentData,
        "text": text,
        "likes": likes,
        "date": Timestamp(date:date)
      ]
    }
}
