//
//  Post.swift
//  projectX
//
//  Created by Radomyr Bezghin on 9/10/20.
//  Copyright © 2020 Radomyr Bezghin. All rights reserved.
//

import FirebaseFirestore

struct Post{
    /// A unique ID identifying the post, generated by Firestore.
    var documentID: String

    /// station where post is posted.
    var stationID: String

    /// The name of the station.
    var stationName: String

    /// The number of likes of the post.
    var likes: Int

    /// User information duplicated in the post object.
    var userInfo: User

    /// The title of the post.
    var title: String
    
    /// The body text of the post.
    var text: String

    /// The date the review was posted.
    var date: Date
    
    /// Post photo url stored in the Firestore
    var imageURL: URL?
}
extension Post{
    /// Initializes a post from a dictionary.
    private init?(documentID: String, dictionary: [String : Any]) {
        
        guard let stationID = dictionary["stationID"] as? String else {return nil}
        guard let stationName = dictionary["stationName"] as? String else {return nil}
        guard let likes = dictionary["likes"] as? Int else {return nil}
        guard let userDict = dictionary["userInfo"] as? [String: Any] else {return nil}
        guard let title = dictionary["title"] as? String else {return nil}
        guard let text = dictionary["text"] as? String else {return nil}
        guard let timestamp = dictionary["date"] as? Timestamp else {return nil}
        let imageURL = dictionary["imageURL"] as? URL ?? nil
        
        guard let userInfo = User(dictionary: userDict) else {return nil}
        
        self.init(documentID: documentID,
                  stationID: stationID,
                  stationName: stationName,
                  likes: likes,
                  userInfo: userInfo,
                  title: title,
                  text: text,
                  date: timestamp.dateValue(),
                  imageURL: imageURL)
    }

//    public init?(document: QueryDocumentSnapshot) {
//      self.init(documentID: document.documentID, dictionary: document.data())
//    }

    public init?(document: DocumentSnapshot) {
      guard let data = document.data() else { return nil }
      self.init(documentID: document.documentID, dictionary: data)
    }
    /// returns a new post object 
    public init(stationID: String,
                stationName: String,
                likes: Int,
                userInfo: User,
                title: String,
                text: String,
                date: Date,
                imageURL: URL?) {
        let document = Firestore.firestore().posts.document() // returns a brand new document
        documentID = document.documentID
        self.stationID = stationID
        self.stationName = stationName
        self.likes = likes
        self.userInfo = userInfo
        self.title = title
        self.text = text
        self.date = date
        self.imageURL = imageURL
    }
    /// used to generate json like format for db
    var documentData: [String: Any] {
      return [
        "stationID": stationID,
        "stationName": stationName,
        "likes": likes,
        "userInfo": userInfo.documentData,
        "title": title,
        "text": text,
        "date": Timestamp(date:date),
        "imageURL": imageURL
      ]
    }
}
    
