//
//  Post.swift
//  projectX
//
//  Created by Radomyr Bezghin on 9/10/20.
//  Copyright © 2020 Radomyr Bezghin. All rights reserved.
//

import FirebaseFirestore

struct Post{
    /// A unique ID identifying the post, generated by Firestore.
    var documentID: String

    /// station where post is posted.
    var stationID: String

    /// The name of the station.
    var stationName: String

    /// The number of likes of the post.
    var likes: Int

    /// User information duplicated in the post object.
    var userInfo: User

    /// The title of the post.
    var title: String
    
    /// The body text of the post.
    var text: String

    /// The date the review was posted.
    var date: Date
    
    /// Post photo url stored in the Firestore
    var imageURL: URL?
}
extension Post{
    public init(stationID: String,
                stationName: String,
                likes: Int,
                userInfo: User,
                title: String,
                text: String,
                date: Date,
                imageURL: URL?) {
        let document = Firestore.firestore().posts.document() // returns a brand new document
        documentID = document.documentID
        self.stationID = stationID
        self.stationName = stationName
        self.likes = likes
        self.userInfo = userInfo
        self.title = title
        self.text = text
        self.date = date
        self.imageURL = imageURL
    }
    /// used to generate json like format for db
    var documentData: [String: Any] {
      return [
        "stationID": stationID,
        "stationName": stationName,
        "likes": likes,
        "userInfo": "not implemented",
        "title": title,
        "text": text,
        "date": Timestamp(date:date),
        "imageURL": imageURL
      ]
    }
}
//MARK: static data
extension Post{
    static let defaultImageURL = URL(string: "https://firebasestorage.googleapis.com/v0/b/projectx-e4848.appspot.com/o/sslug.jpg?alt=media&token=aa2bda56-f5bc-4cc5-b9a2-ca37a6b4b7ae")!
}
    
