//
//  Station.swift
//  projectX
//
//  Created by Radomyr Bezghin on 9/10/20.
//  Copyright © 2020 Radomyr Bezghin. All rights reserved.
//

import FirebaseFirestore

struct Station{
    /// A unique ID identifying the station, generated by Firestore.
    var documentID: String

    /// brief description of the station.
    var info: String

    /// The name of the station.
    var stationName: String

    /// The number of followers of the station.
    var followers: Int

    /// The date when station was created.
    var date: Date
    
    /// Station photo url stored in the Firestore
    var imageURL: URL?
}
extension Station{
    public init(info: String,
                stationName: String,
                followers: Int,
                date: Date,
                imageURL: URL?) {
        let document = Firestore.firestore().stations.document() // returns a brand new document
        documentID = document.documentID
        self.info = info
        self.stationName = stationName
        self.followers = followers
        self.date = date
        self.imageURL = imageURL
    }
    /// used to generate json like format for db
    var documentData: [String: Any] {
      return [
        "info": info,
        "stationName": stationName,
        "followers": followers,
        "date": Timestamp(date:date),
        "imageURL": imageURL
      ]
    }
}
